CREATE TABLE IF NOT EXISTS URL (
  id SERIAL PRIMARY KEY,
  original_url VARCHAR(255) NOT NULL,
  short_code VARCHAR(255) UNIQUE NOT NULL,
  clicks INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP WITH TIME ZONE,
  last_accessed TIMESTAMP WITH TIME ZONE
);
