services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    volumes:
      - .:/app 
      - /app/node_modules
    environment:
      TEST_DB_URL: postgresql://postgres:password@postgres:5432/testdb
      NODE_ENV: test
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
